export const KAFKA_CLIENT_OPTIONS = Symbol('KAFKA_CLIENT_OPTIONS');
export const PARTIAL_KAFKA_CONSUMER_OPTIONS = Symbol('KAFKA_CONSUMER_OPTIONS');
export const PARTIAL_KAFKA_PRODUCER_OPTIONS = Symbol('KAFKA_PRODUCER_OPTIONS');
